apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "usecase-frontend.fullname" . }}
  labels:
    {{- include "usecase-frontend.labels" . | nindent 4 }}
{{- with .Values.ConfigMap }}
data:
  {{- toYaml . | nindent 2 }}
{{- end }}
